// GENERATED by dashboard_src/build.py from common.jsx + tab_bilateral.jsx + tab_country.jsx + tab_world.jsx + trade.page.jsx — edit those, not this file.
// ─────────────────────────────────────────────────────────────────────────────
// Shared UI kit for the ITPD-E dashboards. Dashboard components can only import
// React and @malloyyo/dashboard, so dashboard_src/build.py inlines this file at
// the top of each dashboards/<name>.jsx. Edit here, then run the build script.
// ─────────────────────────────────────────────────────────────────────────────
import React, { useEffect, useMemo, useState } from "react";
import { VegaChart, Range, useGiven, useOptions, useQuery, useUrlState, filters } from "@malloyyo/dashboard";

// ── Palette (validated with the dataviz validator, light + dark) ────────────
const PAL = {
  light: {
    A: "#2a78d6", B: "#eb6834",
    sectors: { Agriculture: "#1baf7a", "Mining and Energy": "#eda100", Manufacturing: "#e87ba4", Services: "#4a3aa7" },
    regions: { Africa: "#1baf7a", Americas: "#4a3aa7", Asia: "#eda100", Europe: "#e87ba4", Oceania: "#008300", Other: "#b5b3ab" },
    ink: "#0b0b0b", ink2: "#52514e", muted: "#898781", grid: "#e1e0d9", axis: "#c3c2b7", surface: "#fcfcfb",
    good: "#006300", bad: "#d03b3b",
    seq: ["#cde2fb", "#9ec5f4", "#6da7ec", "#3987e5", "#256abf", "#184f95", "#0d366b"],
  },
  dark: {
    A: "#3987e5", B: "#d95926",
    sectors: { Agriculture: "#199e70", "Mining and Energy": "#c98500", Manufacturing: "#d55181", Services: "#9085e9" },
    regions: { Africa: "#199e70", Americas: "#9085e9", Asia: "#c98500", Europe: "#d55181", Oceania: "#008300", Other: "#5d5c57" },
    ink: "#ffffff", ink2: "#c3c2b7", muted: "#898781", grid: "#2c2c2a", axis: "#383835", surface: "#1a1a19",
    good: "#0ca30c", bad: "#e66767",
    seq: ["#184f95", "#1c5cab", "#256abf", "#2a78d6", "#3987e5", "#6da7ec", "#9ec5f4"],
  },
};
const SECTORS = ["Agriculture", "Mining and Energy", "Manufacturing", "Services"];
const REGIONS = ["Africa", "Americas", "Asia", "Europe", "Oceania", "Other"];

function useDark() {
  const q = typeof window !== "undefined" && window.matchMedia ? window.matchMedia("(prefers-color-scheme: dark)") : null;
  const [dark, setDark] = useState(q ? q.matches : false);
  useEffect(() => {
    if (!q) return undefined;
    const on = (e) => setDark(e.matches);
    q.addEventListener ? q.addEventListener("change", on) : q.addListener(on);
    return () => (q.removeEventListener ? q.removeEventListener("change", on) : q.removeListener(on));
  }, []);
  return dark;
}
function usePalette() {
  return useDark() ? PAL.dark : PAL.light;
}

// ── Formatting ───────────────────────────────────────────────────────────────
// Every dashboard query returns money in millions of US dollars (usd_m).
function fmtUSD(m, digits) {
  if (m == null || isNaN(m)) return "–";
  const a = Math.abs(m);
  const s = m < 0 ? "−" : "";
  const d = digits ?? (a >= 1e6 ? 2 : 1);
  if (a >= 1e6) return `${s}$${(a / 1e6).toFixed(d)}T`;
  if (a >= 1e3) return `${s}$${(a / 1e3).toFixed(a >= 1e5 ? 0 : d)}B`;
  if (a >= 1) return `${s}$${a.toFixed(a >= 100 ? 0 : d)}M`;
  if (a > 0) return `${s}$${Math.round(a * 1000)}K`;
  return "$0";
}
const fmtPct = (x, d = 1) => (x == null || isNaN(x) ? "–" : `${(x * 100).toFixed(d)}%`);
const fmtNum = (x) => (x == null || isNaN(x) ? "–" : Math.round(x).toLocaleString("en-US"));
// ITPD-E services industries carry a numeric prefix ("163 Other business services").
const cleanIndustry = (s) => String(s ?? "").replace(/^\d+\s+/, "");
// A filter<string> given holds a filter EXPRESSION; unwrap it to the picked value.
function pickedValue(v) {
  if (v == null || v === "") return "";
  const vals = filters.values(String(v));
  return vals && vals.length ? vals[0] : String(v);
}
const cagr = (first, last, years) =>
  first > 0 && last > 0 && years > 0 ? Math.pow(last / first, 1 / years) - 1 : null;

// ── Styles ───────────────────────────────────────────────────────────────────
const CSS = `
.tx{--bg:#f4f3ef;--card:#fcfcfb;--ink:#0b0b0b;--ink2:#52514e;--muted:#898781;--line:rgba(11,11,11,.09);
  --hero1:#0b1d33;--hero2:#123a63;--chip:#eceae4;--A:#2a78d6;--B:#eb6834;--good:#006300;--bad:#c22f2f;
  --shadow:0 1px 2px rgba(16,24,40,.05),0 4px 16px rgba(16,24,40,.06);
  --dash-accent:#2a78d6;--dash-radius:10px;
  font:14px/1.45 system-ui,-apple-system,"Segoe UI",sans-serif;color:var(--ink);background:var(--bg);min-height:100vh}
@media (prefers-color-scheme: dark){
  .tx{--bg:#0d0d0d;--card:#1a1a19;--ink:#fff;--ink2:#c3c2b7;--muted:#9a988f;--line:rgba(255,255,255,.10);
    --hero1:#07111f;--hero2:#0f2c4b;--chip:#26262a;--A:#3987e5;--B:#d95926;--good:#0ca30c;--bad:#e66767;
    --shadow:0 1px 2px rgba(0,0,0,.4);--dash-accent:#3987e5}
}
.tx *{box-sizing:border-box}
.tx-hero{background:radial-gradient(1200px 400px at 85% -10%,rgba(57,135,229,.35),transparent 60%),
  radial-gradient(900px 380px at 5% 120%,rgba(235,104,52,.22),transparent 60%),
  linear-gradient(135deg,var(--hero1),var(--hero2));color:#fff;padding:28px 32px 26px;position:relative;overflow:hidden}
.tx-hero:after{content:"";position:absolute;inset:0;background-image:radial-gradient(rgba(255,255,255,.08) 1px,transparent 1px);
  background-size:22px 22px;mask-image:linear-gradient(to bottom,rgba(0,0,0,.6),transparent 85%);pointer-events:none}
.tx-hero>*{position:relative;z-index:1}
.tx-eyebrow{font-size:11.5px;letter-spacing:.12em;text-transform:uppercase;color:#9cc3f0;font-weight:600}
.tx-title{font-size:30px;line-height:1.15;font-weight:700;margin:6px 0 6px;letter-spacing:-.01em}
.tx-sub{color:#c9d6e6;max-width:820px;margin:0}
.tx-controls{margin-top:20px;background:rgba(255,255,255,.96);color:#0b0b0b;border-radius:14px;padding:14px 16px;
  display:flex;flex-wrap:wrap;gap:14px 18px;align-items:flex-end;box-shadow:0 10px 30px rgba(0,0,0,.25)}
@media (prefers-color-scheme: dark){.tx-controls{background:rgba(26,26,25,.97);color:#fff}}
.tx-field{display:flex;flex-direction:column;gap:5px;min-width:150px}
.tx-field label{font-size:11px;font-weight:650;letter-spacing:.06em;text-transform:uppercase;color:var(--muted);display:flex;align-items:center;gap:6px}
.tx-field select{appearance:none;-webkit-appearance:none;font:inherit;font-size:14.5px;font-weight:550;color:inherit;
  background:transparent url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 24 24' fill='none' stroke='%23898781' stroke-width='2.5'%3E%3Cpath d='m6 9 6 6 6-6'/%3E%3C/svg%3E") no-repeat right 10px center;
  border:1px solid var(--line);border-radius:10px;padding:9px 32px 9px 12px;width:210px;text-overflow:ellipsis;cursor:pointer}
.tx-field select:hover{border-color:var(--muted)}
.tx-field select:focus{outline:2px solid var(--dash-accent);outline-offset:1px}
.tx-dot{width:10px;height:10px;border-radius:50%;display:inline-block;flex:none}
.tx-swap{border:1px solid var(--line);background:var(--card);color:inherit;border-radius:999px;width:38px;height:38px;cursor:pointer;
  font-size:17px;display:grid;place-items:center;transition:transform .2s;margin-bottom:1px}
.tx-swap:hover{transform:rotate(180deg)}
.tx-range{min-width:230px;flex:1;max-width:330px}
.tx-range>div>div:first-child{font-size:11px!important;font-weight:650;letter-spacing:.06em;text-transform:uppercase;color:var(--muted)!important}
.tx-try{margin-top:12px;display:flex;flex-wrap:wrap;gap:8px;align-items:center;color:#c9d6e6;font-size:12.5px}
.tx-try button{font:inherit;font-size:12.5px;color:#fff;background:rgba(255,255,255,.10);border:1px solid rgba(255,255,255,.18);
  border-radius:999px;padding:4px 11px;cursor:pointer}
.tx-try button:hover{background:rgba(255,255,255,.2)}
.tx-chips{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}
.tx-chip{font-size:12px;padding:3px 10px;border-radius:999px;background:rgba(255,255,255,.12);border:1px solid rgba(255,255,255,.16);color:#e6eef8}
.tx-body{padding:22px 32px 40px;max-width:1440px;margin:0 auto}
.tx-grid{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:18px}
.tx-card{grid-column:span 6;background:var(--card);border:1px solid var(--line);border-radius:16px;padding:18px 20px 16px;box-shadow:var(--shadow);min-width:0}
.tx-card.w12{grid-column:span 12}.tx-card.w8{grid-column:span 8}.tx-card.w4{grid-column:span 4}.tx-card.w7{grid-column:span 7}.tx-card.w5{grid-column:span 5}
@media (max-width:1000px){.tx-card,.tx-card.w8,.tx-card.w4,.tx-card.w7,.tx-card.w5{grid-column:span 12}}
.tx-card h3{margin:0;font-size:15.5px;font-weight:650;letter-spacing:-.005em}
.tx-card .tx-cardsub{margin:3px 0 12px;color:var(--ink2);font-size:13px}
.tx-kpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:14px;margin-bottom:18px}
.tx-kpi{background:var(--card);border:1px solid var(--line);border-radius:16px;padding:15px 18px;box-shadow:var(--shadow);position:relative;overflow:hidden}
.tx-kpi:before{content:"";position:absolute;left:0;top:0;bottom:0;width:4px;background:var(--accent,transparent)}
.tx-kpi .l{font-size:12px;color:var(--ink2);font-weight:550;display:flex;gap:6px;align-items:center}
.tx-kpi .v{font-size:27px;font-weight:700;letter-spacing:-.02em;margin-top:4px}
.tx-kpi .s{font-size:12.5px;color:var(--muted);margin-top:2px}
.tx-up{color:var(--good);font-weight:600}.tx-down{color:var(--bad);font-weight:600}
.tx-explain{margin-top:12px;display:flex;gap:10px;padding:10px 12px;border-radius:12px;background:var(--chip);color:var(--ink2);font-size:12.8px}
.tx-explain b{color:var(--ink)}
.tx-explain .i{flex:none;width:20px;height:20px;border-radius:50%;background:var(--dash-accent);color:#fff;display:grid;place-items:center;font-size:12px;font-weight:700;font-style:normal}
.tx-legend{display:flex;flex-wrap:wrap;gap:14px;font-size:12.5px;color:var(--ink2);margin:-4px 0 6px}
.tx-legend span{display:inline-flex;align-items:center;gap:6px}
.tx-bars{display:flex;flex-direction:column;gap:7px}
.tx-bar{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:2px 10px;align-items:center;padding:5px 8px;margin:0 -8px;border-radius:9px;cursor:default}
.tx-bar.click{cursor:pointer}.tx-bar.click:hover{background:var(--chip)}
.tx-bar .n{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:13.2px}
.tx-bar .x{font-size:13px;font-weight:650;font-variant-numeric:tabular-nums;text-align:right}
.tx-bar .t{grid-column:1/3;height:7px;border-radius:4px;background:var(--chip);overflow:hidden}
.tx-bar .t i{display:block;height:100%;border-radius:4px}
.tx-bar .m{font-size:11.5px;color:var(--muted);font-weight:500;margin-left:6px}
.tx-tag{font-size:10.5px;padding:1px 7px;border-radius:999px;border:1px solid var(--line);color:var(--ink2);margin-left:6px;white-space:nowrap}
.tx-skel{border-radius:12px;background:linear-gradient(90deg,var(--chip) 0%,rgba(127,127,127,.08) 50%,var(--chip) 100%);background-size:200% 100%;animation:txs 1.2s infinite}
@keyframes txs{0%{background-position:200% 0}100%{background-position:-200% 0}}
.tx-empty{padding:28px;text-align:center;color:var(--muted)}
.tx-facts{display:grid;grid-template-columns:1fr 1fr;gap:10px}
.tx-fact{border:1px solid var(--line);border-radius:12px;padding:10px 12px}
.tx-fact .k{font-size:11.5px;color:var(--muted);font-weight:600;text-transform:uppercase;letter-spacing:.05em}
.tx-fact .v{font-size:16px;font-weight:650;margin-top:2px}
.tx-yes{color:var(--good)}.tx-no{color:var(--muted)}
.tx-stat{display:flex;gap:22px;flex-wrap:wrap;margin:2px 0 10px}
.tx-stat div{font-size:12px;color:var(--ink2)}.tx-stat b{display:block;font-size:20px;color:var(--ink);letter-spacing:-.01em}
.tx-foot{margin-top:26px;color:var(--muted);font-size:12px;line-height:1.6;border-top:1px solid var(--line);padding-top:14px}
.tx-two{display:grid;grid-template-columns:1fr 1fr;gap:22px}
@media (max-width:800px){.tx-two{grid-template-columns:1fr}.tx-facts{grid-template-columns:1fr}}
.tx-colhead{font-size:12.5px;font-weight:650;margin-bottom:8px;display:flex;align-items:center;gap:7px}
.tx-heat{width:100%;border-collapse:separate;border-spacing:3px;font-size:12px}
.tx-heat th{font-weight:600;color:var(--ink2);text-align:left;padding:4px 6px;font-size:11.5px}
.tx-heat td{text-align:center;padding:9px 4px;border-radius:7px;font-weight:600;font-variant-numeric:tabular-nums}
`;

// ── Layout pieces ────────────────────────────────────────────────────────────
function Shell({ children }) {
  return (
    <div className="tx">
      <style>{CSS}</style>
      {children}
    </div>
  );
}
function Hero({ eyebrow, title, sub, children }) {
  return (
    <header className="tx-hero">
      <div className="tx-eyebrow">{eyebrow}</div>
      <h1 className="tx-title">{title}</h1>
      <p className="tx-sub">{sub}</p>
      {children}
    </header>
  );
}
function Card({ w = 6, title, sub, children, style }) {
  return (
    <section className={`tx-card w${w}`} style={style}>
      {title && <h3>{title}</h3>}
      {sub ? <p className="tx-cardsub">{sub}</p> : <div style={{ height: 10 }} />}
      {children}
    </section>
  );
}
function Kpi({ label, value, sub, accent, dot }) {
  return (
    <div className="tx-kpi" style={{ "--accent": accent }}>
      <div className="l">
        {dot && <span className="tx-dot" style={{ background: dot }} />}
        {label}
      </div>
      <div className="v">{value}</div>
      {sub && <div className="s">{sub}</div>}
    </div>
  );
}
function Explain({ title, children }) {
  return (
    <div className="tx-explain">
      <i className="i">i</i>
      <div>
        {title && <b>{title} </b>}
        {children}
      </div>
    </div>
  );
}
function Skel({ h = 260 }) {
  return <div className="tx-skel" style={{ height: h }} />;
}
function Empty({ children }) {
  return <div className="tx-empty">{children || "No trade recorded for this selection."}</div>;
}
function Legend({ items }) {
  return (
    <div className="tx-legend">
      {items.map((it) => (
        <span key={it.label}>
          <span className="tx-dot" style={{ background: it.color, borderRadius: it.square ? 3 : "50%" }} />
          {it.label}
        </span>
      ))}
    </div>
  );
}
function Delta({ value, suffix = "", invert }) {
  if (value == null || isNaN(value)) return null;
  const up = value >= 0;
  const good = invert ? !up : up;
  return (
    <span className={good ? "tx-up" : "tx-down"}>
      {up ? "▲" : "▼"} {Math.abs(value * 100).toFixed(1)}%{suffix}
    </span>
  );
}

// Horizontal bar list (HTML, so rows can be clicked to drive a given).
function BarList({ rows, color, onPick, pickHint, max }) {
  const top = max ?? Math.max(...rows.map((r) => r.value), 0);
  return (
    <div className="tx-bars">
      {rows.map((r) => (
        <div
          key={r.key ?? r.label}
          className={`tx-bar${onPick ? " click" : ""}`}
          onClick={onPick ? () => onPick(r) : undefined}
          title={onPick ? pickHint?.(r) : undefined}
        >
          <div className="n">
            {r.label}
            {r.tag && <span className="tx-tag">{r.tag}</span>}
            {r.meta && <span className="m">{r.meta}</span>}
          </div>
          <div className="x">{r.display}</div>
          <div className="t">
            <i style={{ width: `${top > 0 ? Math.max(1.5, (r.value / top) * 100) : 0}%`, background: r.color || color }} />
          </div>
        </div>
      ))}
    </div>
  );
}

// ── Controls ─────────────────────────────────────────────────────────────────
// A dropdown bound to a filter<string> given, fed by the given's suggest query.
// allowAll adds an "All" (empty filter) option; country pickers omit it.
function GivenSelect({ given, label, dot, allowAll, allLabel = "All", format }) {
  const { value, set } = useGiven(given);
  const { options } = useOptions(given);
  const current = pickedValue(value);
  const opts = (options || []).map((o) => (typeof o === "object" ? (o.text ?? o.value) : String(o)));
  if (current && !opts.includes(current)) opts.unshift(current);
  return (
    <div className="tx-field">
      <label>
        {dot && <span className="tx-dot" style={{ background: dot }} />}
        {label}
      </label>
      <select value={current} onChange={(e) => set(e.target.value ? filters.oneOf(e.target.value) : "")}>
        {allowAll && <option value="">{allLabel}</option>}
        {opts.map((o) => (
          <option key={o} value={o}>
            {format ? format(o) : o}
          </option>
        ))}
      </select>
    </div>
  );
}
// Sector + industry pair: the industry list narrows to the chosen sector, and a
// sector change clears an industry that no longer belongs to it.
function SectorIndustry({ prefix }) {
  const sector = useGiven(`${prefix}_SECTOR`);
  const industry = useGiven(`${prefix}_INDUSTRY`);
  const [prev, setPrev] = useState(sector.value);
  useEffect(() => {
    if (sector.value !== prev) {
      setPrev(sector.value);
      if (industry.value) industry.set("");
    }
  }, [sector.value]);
  return (
    <>
      <GivenSelect given={`${prefix}_SECTOR`} label="Sector" allowAll allLabel="All sectors" />
      <GivenSelect given={`${prefix}_INDUSTRY`} label="Industry (optional)" allowAll allLabel="All industries" format={cleanIndustry} />
    </>
  );
}
function YearRange({ prefix }) {
  return (
    <div className="tx-range">
      <Range given={`${prefix}_YEAR_RANGE`} label="Years" />
    </div>
  );
}

// ── Vega-Lite helpers ────────────────────────────────────────────────────────
function vegaConfig(p) {
  return {
    background: null,
    font: 'system-ui, -apple-system, "Segoe UI", sans-serif',
    view: { stroke: null },
    axis: {
      labelColor: p.muted, titleColor: p.ink2, gridColor: p.grid, domainColor: p.axis, tickColor: p.axis,
      labelFontSize: 11.5, titleFontSize: 11.5, titleFontWeight: 500, labelPadding: 6, gridWidth: 1,
    },
    axisX: { grid: false, tickCount: 8 },
    axisY: { domain: false, ticks: false, tickCount: 5 },
    legend: { disable: true },
    text: { color: p.ink2, fontSize: 11.5 },
  };
}
// Axis label expression: billions of USD in, "$1.2T" / "$350B" / "$4B" out.
const BN_LABEL =
  "datum.value >= 1000 || datum.value <= -1000 ? (datum.value < 0 ? '−' : '') + '$' + format(abs(datum.value) / 1000, '.1~f') + 'T' : (datum.value < 0 ? '−' : '') + '$' + format(abs(datum.value), datum.value != 0 && abs(datum.value) < 10 ? '.1~f' : '.0f') + 'B'";
// Same, for tooltips/labels from a field named in `f` (billions).
const bnText = (f) =>
  `(abs(datum.${f}) >= 1000 ? '$' + format(datum.${f} / 1000, '.2~f') + 'T' : abs(datum.${f}) >= 1 ? '$' + format(datum.${f}, '.1~f') + 'B' : '$' + format(datum.${f} * 1000, '.0f') + 'M')`;

// Multi-series line chart with a hover crosshair that prints each series' value.
// rows: [{year, key, label, v}] — v already in the unit `fmt` expects.
function lineSpec({ p, keys, colors, labels, yTitle, yFormat, valueText, height = 260, yZero = true }) {
  const color = { field: "key", type: "nominal", scale: { domain: keys, range: colors }, legend: null };
  return {
    height,
    config: vegaConfig(p),
    encoding: {
      x: { field: "year", type: "quantitative", title: null, axis: { format: "d", tickMinStep: 1 }, scale: { nice: false } },
    },
    layer: [
      {
        mark: { type: "line", strokeWidth: 2.25, interpolate: "monotone", strokeCap: "round" },
        encoding: {
          y: { field: "v", type: "quantitative", title: yTitle, scale: { zero: yZero }, axis: yFormat ? { labelExpr: yFormat } : { format: "~s" } },
          color,
        },
      },
      {
        params: [{ name: "hov", select: { type: "point", fields: ["year"], nearest: true, on: "pointermove", clear: "pointerout" } }],
        mark: { type: "rule", strokeWidth: 1, color: p.axis },
        encoding: { opacity: { condition: { param: "hov", empty: false, value: 1 }, value: 0 } },
      },
      {
        transform: [{ filter: { param: "hov", empty: false } }],
        mark: { type: "point", filled: true, size: 70, stroke: p.surface, strokeWidth: 2 },
        encoding: { y: { field: "v", type: "quantitative" }, color },
      },
      {
        transform: [
          { filter: { param: "hov", empty: false } },
          { calculate: valueText, as: "txt" },
        ],
        mark: { type: "text", align: "left", dx: 9, fontWeight: 650, fontSize: 12, color: p.ink },
        encoding: {
          y: { field: "v", type: "quantitative" },
          text: { field: "txt" },
        },
      },
      {
        transform: [{ filter: { param: "hov", empty: false } }, { aggregate: [{ op: "count", as: "n" }], groupby: ["year"] }],
        mark: { type: "text", y: -6, fontWeight: 700, fontSize: 12, color: p.ink },
        encoding: { text: { field: "year", type: "quantitative", format: "d" } },
      },
    ],
  };
}

// Run a named query in this dashboard file with ONLY the givens its tab uses,
// so changing a filter on one tab never re-runs another tab's queries.
function pickGivens(givens, keys) {
  const out = {};
  for (const k of keys) if (givens[k] !== undefined) out[k] = givens[k];
  return out;
}
function useRows(query, givens) {
  return useQuery({ query, givens });
}
// Flatten a one-row-per-year result with a nested array into flat rows.
function unnest(rows, key) {
  const out = [];
  for (const r of rows) for (const x of r[key] || []) out.push({ ...x, year: r.year });
  return out;
}
// Latest year present in a row set (optionally capped, e.g. DGD ends in 2019).
function latestYear(rows, cap) {
  let y = null;
  for (const r of rows) if ((cap == null || r.year <= cap) && (y == null || r.year > y)) y = r.year;
  return y;
}
function firstYear(rows) {
  let y = null;
  for (const r of rows) if (y == null || r.year < y) y = r.year;
  return y;
}

function Footer() {
  return (
    <footer className="tx-foot">
      <b>Data:</b> USITC International Trade and Production Database for Estimation (ITPD-E), release 2025 — trade in current US
      dollars, 170 industries, 1986–2023, including domestic sales (excluded from the cross-border figures here). Gravity
      variables: USITC Dynamic Gravity Dataset 2.1 (1986–2019). Regions: UN M49. Income groups: World Bank. Coverage: agriculture
      from 1986, manufacturing and mining & energy from 1988, services from 2000; services methodology changes in 2004 and 2010
      cause visible jumps. Domestic (home-market) sales are complete only through 2021.
    </footer>
  );
}

// ── Bilateral Trade Explorer ─────────────────────────────────────────────────
const TRY_PAIRS = [
  ["United States", "China"],
  ["Germany", "France"],
  ["United States", "Mexico"],
  ["Japan", "Korea, South"],
  ["Brazil", "Argentina"],
  ["Australia", "China"],
  ["Russia", "Ukraine"],
];

function byYearDir(rows, field = "usd_m") {
  const m = new Map();
  for (const r of rows) {
    const o = m.get(r.year) || { year: r.year, AB: 0, BA: 0 };
    o[r.direction] += r[field] || 0;
    m.set(r.year, o);
  }
  return [...m.values()].sort((a, b) => a.year - b.year);
}

function PairFacts({ rows, aName, bName, p }) {
  if (!rows.length) return <Empty>The gravity dataset covers 1986–2019; no pair data for this selection.</Empty>;
  const last = rows[rows.length - 1];
  // First year of the current unbroken run of an indicator (e.g. "agreement since 1994").
  const since = (f) => {
    if (!last[f]) return null;
    let y = last.year;
    for (let i = rows.length - 1; i >= 0 && rows[i][f]; i--) y = rows[i].year;
    return y;
  };
  const yn = (v, extra) => (
    <span className={v ? "tx-yes" : "tx-no"}>
      {v ? "Yes" : "No"}
      {v && extra ? <span style={{ color: "var(--muted)", fontWeight: 500, fontSize: 13 }}> · {extra}</span> : null}
    </span>
  );
  const pta = since("agree_pta");
  const gdpRow = [...rows].reverse().find((r) => r.a_gdp_bn || r.b_gdp_bn) || last;
  const bothWto = last.a_wto && last.b_wto;
  let wtoSince = null;
  if (bothWto) {
    wtoSince = last.year;
    for (let i = rows.length - 1; i >= 0 && rows[i].a_wto && rows[i].b_wto; i--) wtoSince = rows[i].year;
  }
  const kind = last.agree_cu ? "customs union" : last.agree_fta ? "free trade agreement" : last.agree_pta ? "preferential agreement" : null;
  return (
    <>
      <div className="tx-facts">
        <div className="tx-fact">
          <div className="k">Distance</div>
          <div className="v">{fmtNum(last.distance_km)} km</div>
        </div>
        <div className="tx-fact">
          <div className="k">Shared border</div>
          <div className="v">{yn(last.contiguity)}</div>
        </div>
        <div className="tx-fact">
          <div className="k">Common language</div>
          <div className="v">{yn(last.common_language)}</div>
        </div>
        <div className="tx-fact">
          <div className="k">Colonial tie (ever)</div>
          <div className="v">{yn(last.colony_ever)}</div>
        </div>
        <div className="tx-fact">
          <div className="k">Trade agreement ({last.year})</div>
          <div className="v">{yn(pta, kind && pta ? `${kind}, since ${pta}` : null)}</div>
        </div>
        <div className="tx-fact">
          <div className="k">Both in GATT/WTO</div>
          <div className="v">{yn(bothWto, wtoSince ? `since ${wtoSince <= 1995 && rows[0].year === wtoSince ? "≤" : ""}${wtoSince}` : null)}</div>
        </div>
        <div className="tx-fact">
          <div className="k">
            <span className="tx-dot" style={{ background: p.A, marginRight: 6 }} />
            {aName} GDP ({gdpRow.year})
          </div>
          <div className="v">{gdpRow.a_gdp_bn ? fmtUSD(gdpRow.a_gdp_bn * 1000) : "–"}</div>
        </div>
        <div className="tx-fact">
          <div className="k">
            <span className="tx-dot" style={{ background: p.B, marginRight: 6 }} />
            {bName} GDP ({gdpRow.year})
          </div>
          <div className="v">{gdpRow.b_gdp_bn ? fmtUSD(gdpRow.b_gdp_bn * 1000) : "–"}</div>
        </div>
      </div>
      <Explain title="The gravity model.">
        Like Newton's law of gravity, trade between two countries tends to rise with the size of both economies (GDP) and fall
        with the distance between them: <i>Trade ≈ G × GDP<sub>A</sub> × GDP<sub>B</sub> / Distance</i>. Shared borders,
        languages, colonial history and trade agreements all push trade above what size and distance alone predict.
      </Explain>
    </>
  );
}

const B_KEYS = ['COUNTRY_A', 'COUNTRY_B', 'B_SECTOR', 'B_INDUSTRY', 'B_YEAR_RANGE'];

function BilateralTab({ givens: allGivens }) {
  const givens = useMemo(() => pickGivens(allGivens, B_KEYS), [JSON.stringify(pickGivens(allGivens, B_KEYS))]);
  const p = usePalette();
  const A = useGiven("COUNTRY_A");
  const B = useGiven("COUNTRY_B");
  const IND = useGiven("B_INDUSTRY");
  const aName = pickedValue(A.value) || "Country A";
  const bName = pickedValue(B.value) || "Country B";
  const industry = cleanIndustry(pickedValue(givens.B_INDUSTRY));
  const sector = pickedValue(givens.B_SECTOR);
  const same = aName === bName;

  const flows = useRows("b_flows_by_year", givens);
  const sectors = useRows("b_sector_by_year", givens);
  const indsQ = useRows("b_industries_by_year", givens);
  const inds = useMemo(() => ({ loading: indsQ.loading, rows: unnest(indsQ.rows, "industries") }), [indsQ.rows, indsQ.loading]);
  const share = useRows("b_partner_share_by_year", givens);
  const facts = useRows("b_pair_facts_by_year", givens);
  const who = useRows("b_pair_countries", givens);

  const years = useMemo(() => byYearDir(flows.rows), [flows.rows]);
  const L = years.length ? years[years.length - 1] : null;
  const F = years.find((y) => y.AB + y.BA > 0) || null;
  const growth = L && F && L.year > F.year ? cagr(F.AB + F.BA, L.AB + L.BA, L.year - F.year) : null;
  const balance = L ? L.AB - L.BA : null;
  const selection = industry || sector || "all goods & services";

  const lineRows = useMemo(
    () =>
      years.flatMap((y) => [
        { year: y.year, key: "AB", v: y.AB / 1000 },
        { year: y.year, key: "BA", v: y.BA / 1000 },
      ]),
    [years],
  );
  const balRows = useMemo(() => years.map((y) => ({ year: y.year, v: (y.AB - y.BA) / 1000, side: y.AB >= y.BA ? "A" : "B" })), [years]);

  const shareRows = useMemo(
    () => share.rows.map((r) => ({ year: r.year, key: r.direction, v: r.world_m > 0 ? r.partner_m / r.world_m : null })).filter((r) => r.v != null),
    [share.rows],
  );

  // Industries in the latest year + Grubel–Lloyd intra-industry trade index.
  const indLatest = useMemo(() => {
    const y = latestYear(inds.rows);
    const rows = inds.rows.filter((r) => r.year === y);
    const ab = rows.filter((r) => r.direction === "AB").sort((a, b) => b.usd_m - a.usd_m);
    const ba = rows.filter((r) => r.direction === "BA").sort((a, b) => b.usd_m - a.usd_m);
    const m = new Map();
    for (const r of rows) {
      const o = m.get(r.industry_descr) || { x: 0, mm: 0 };
      if (r.direction === "AB") o.x += r.usd_m;
      else o.mm += r.usd_m;
      m.set(r.industry_descr, o);
    }
    let num = 0,
      den = 0;
    for (const o of m.values()) {
      num += Math.abs(o.x - o.mm);
      den += o.x + o.mm;
    }
    return { year: y, ab, ba, gl: den > 0 ? 1 - num / den : null };
  }, [inds.rows]);

  const sectorRows = (dir) => sectors.rows.filter((r) => r.direction === dir).map((r) => ({ year: r.year, sector: r.broad_sector, so: SECTORS.indexOf(r.broad_sector), v: r.usd_m / 1000 }));

  const lspec = useMemo(
    () => lineSpec({ p, keys: ["AB", "BA"], colors: [p.A, p.B], yTitle: null, yFormat: BN_LABEL, valueText: bnText("v"), height: 340 }),
    [p],
  );
  const sspec = useMemo(
    () =>
      lineSpec({
        p, keys: ["AB", "BA"], colors: [p.A, p.B], yTitle: null, height: 220,
        yFormat: "format(datum.value, '.0%')", valueText: "format(datum.v, '.1%')",
      }),
    [p],
  );
  const bspec = useMemo(
    () => ({
      height: 220,
      config: vegaConfig(p),
      layer: [
        {
          params: [{ name: "hb", select: { type: "point", fields: ["year"], on: "pointerover", clear: "pointerout" } }],
          mark: { type: "bar", cornerRadiusEnd: 3, width: { band: 0.72 } },
          encoding: {
            x: { field: "year", type: "ordinal", title: null, axis: { labelAngle: 0, labelExpr: "datum.value % 5 == 0 ? datum.value : ''" } },
            y: { field: "v", type: "quantitative", title: null, axis: { labelExpr: BN_LABEL } },
            color: { field: "side", type: "nominal", scale: { domain: ["A", "B"], range: [p.A, p.B] }, legend: null },
            opacity: { condition: { param: "hb", empty: true, value: 1 }, value: 0.45 },
          },
        },
        {
          mark: { type: "rule", color: p.axis },
          encoding: { y: { datum: 0 } },
        },
        {
          transform: [{ filter: { param: "hb", empty: false } }, { calculate: `datum.year + ': ' + (datum.v >= 0 ? '+' : '−') + ${bnText("v").replace(/datum\.v/g, "abs(datum.v)")}`, as: "txt" }],
          mark: { type: "text", fontWeight: 650, fontSize: 12, y: -8, color: p.ink },
          encoding: { x: { field: "year", type: "ordinal" }, text: { field: "txt" } },
        },
      ],
    }),
    [p],
  );
  const mixSpec = useMemo(
    () => ({
      height: 190,
      config: vegaConfig(p),
      mark: { type: "bar", width: { band: 0.8 }, stroke: p.surface, strokeWidth: 1 },
      encoding: {
        x: { field: "year", type: "ordinal", title: null, axis: { labelAngle: 0, labelExpr: "datum.value % 5 == 0 ? datum.value : ''" } },
        y: { field: "v", type: "quantitative", stack: "normalize", title: null, axis: { format: ".0%" } },
        color: { field: "sector", type: "nominal", scale: { domain: SECTORS, range: SECTORS.map((s) => p.sectors[s]) }, legend: null },
        order: { field: "so", type: "quantitative", sort: "ascending" },
        tooltip: [
          { field: "year", type: "ordinal", title: "Year" },
          { field: "sector", type: "nominal", title: "Sector" },
          { field: "v", type: "quantitative", title: "Exports ($ billions)", format: ",.2f" },
        ],
      },
    }),
    [p],
  );

  const setPair = (a, b) => {
    A.set(filters.oneOf(a));
    B.set(filters.oneOf(b));
  };
  const swap = () => setPair(bName, aName);
  const chips = who.rows.slice().sort((x, y) => (x.side < y.side ? -1 : 1));

  return (
    <>
      <Hero
        eyebrow="International trade · ITPD-E 1986–2023"
        title={same ? "Bilateral Trade Explorer" : `${aName} ⇄ ${bName}`}
        sub="Pick two economies to see how much they sell to each other, who runs the surplus, what they trade, and how the relationship has changed over time. Narrow it to one sector or industry to see its story."
      >
        <div className="tx-controls">
          <GivenSelect given="COUNTRY_A" label="Country A" dot={p.A} />
          <button className="tx-swap" onClick={swap} title="Swap countries" aria-label="Swap countries">⇄</button>
          <GivenSelect given="COUNTRY_B" label="Country B" dot={p.B} />
          <SectorIndustry prefix="B" />
          <YearRange prefix="B" />
        </div>
        <div className="tx-try">
          Try:
          {TRY_PAIRS.map(([a, b]) => (
            <button key={a + b} onClick={() => setPair(a, b)}>
              {a} ⇄ {b}
            </button>
          ))}
        </div>
        {chips.length > 0 && (
          <div className="tx-chips">
            {chips.map((c) => (
              <span className="tx-chip" key={c.country_name}>
                <span className="tx-dot" style={{ background: c.side === "A" ? p.A : p.B, marginRight: 6, width: 8, height: 8 }} />
                {c.country_name}: {c.sub_region || c.region || "—"}
                {c.wb_income_group_current ? ` · ${c.wb_income_group_current}` : ""}
              </span>
            ))}
            <span className="tx-chip">Showing: {selection}</span>
          </div>
        )}
      </Hero>

      <main className="tx-body">
        {same ? (
          <Card w={12} title="Pick two different countries">
            <Empty>Country A and Country B are the same. Choose a different partner to see bilateral trade.</Empty>
          </Card>
        ) : (
          <>
            <div className="tx-kpis">
              <Kpi
                accent={p.A}
                dot={p.A}
                label={`${aName} → ${bName}`}
                value={L ? fmtUSD(L.AB) : "–"}
                sub={L ? `exports in ${L.year}` : flows.loading ? "loading…" : "no data"}
              />
              <Kpi
                accent={p.B}
                dot={p.B}
                label={`${bName} → ${aName}`}
                value={L ? fmtUSD(L.BA) : "–"}
                sub={L ? `exports in ${L.year}` : ""}
              />
              <Kpi label="Two-way trade" value={L ? fmtUSD(L.AB + L.BA) : "–"} sub={L ? `total in ${L.year}` : ""} />
              <Kpi
                accent={balance == null ? undefined : balance >= 0 ? p.A : p.B}
                label={`${aName}'s trade balance`}
                value={balance == null ? "–" : `${balance >= 0 ? "+" : ""}${fmtUSD(balance)}`}
                sub={balance == null ? "" : balance >= 0 ? `surplus with ${bName}` : `deficit with ${bName}`}
              />
              <Kpi
                label="Growth of two-way trade"
                value={growth == null ? "–" : <Delta value={growth} suffix="/yr" />}
                sub={growth == null ? "" : `compound annual, ${F.year}–${L.year}`}
              />
            </div>

            <div className="tx-grid">
              <Card w={8} title="Exports in each direction" sub={`Annual exports, current US dollars · ${selection}. Hover to read values.`}>
                <Legend items={[{ label: `${aName} → ${bName}`, color: p.A }, { label: `${bName} → ${aName}`, color: p.B }]} />
                {flows.loading && !lineRows.length ? <Skel h={260} /> : lineRows.length ? <VegaChart spec={lspec} data={lineRows} /> : <Empty />}
                <Explain title="Exports = imports, seen from the other side.">
                  {aName}'s exports to {bName} are {bName}'s imports from {aName}. Where one side's report is missing, ITPD-E fills it
                  in from the partner's report (a "mirror" value).
                </Explain>
              </Card>
              <Card w={4} title="Gravity check" sub="What the gravity model says about this pair (USITC Dynamic Gravity Dataset, latest year ≤ 2019).">
                {facts.loading && !facts.rows.length ? <Skel h={300} /> : <PairFacts rows={facts.rows} aName={aName} bName={bName} p={p} />}
              </Card>

              <Card w={6} title={`${aName}'s bilateral trade balance`} sub={`Exports to ${bName} minus imports from ${bName}. Above zero = surplus, below = deficit.`}>
                <Legend items={[{ label: `${aName} surplus`, color: p.A, square: true }, { label: `${bName} surplus`, color: p.B, square: true }]} />
                {flows.loading && !balRows.length ? <Skel h={220} /> : balRows.length ? <VegaChart spec={bspec} data={balRows} /> : <Empty />}
                <Explain title="Is a deficit bad?">
                  Not necessarily. A bilateral deficit means one partner buys more from the other than it sells; what matters for the
                  economy as a whole is the overall balance with all partners, which reflects national saving and investment.
                </Explain>
              </Card>
              <Card w={6} title="How much does each partner matter?" sub="Share of each country's total exports (to all partners, same sector/industry) that goes to the other.">
                <Legend
                  items={[
                    { label: `Share of ${aName}'s exports going to ${bName}`, color: p.A },
                    { label: `Share of ${bName}'s exports going to ${aName}`, color: p.B },
                  ]}
                />
                {share.loading && !shareRows.length ? <Skel h={220} /> : shareRows.length ? <VegaChart spec={sspec} data={shareRows} /> : <Empty />}
                <Explain title="Asymmetric dependence.">
                  A big economy is often a large market for a small partner while the reverse is not true — so a trade dispute can hurt
                  the two sides very differently.
                </Explain>
              </Card>

              <Card
                w={12}
                title={`What do they trade?${indLatest.year ? ` (${indLatest.year})` : ""}`}
                sub="Top industries in each direction. Click an industry to filter the whole page to it."
              >
                {indLatest.gl != null && (
                  <div className="tx-stat">
                    <div>
                      Intra-industry trade (Grubel–Lloyd index)
                      <b>{indLatest.gl.toFixed(2)}</b>
                    </div>
                    <div>
                      Industries traded
                      <b>{new Set([...indLatest.ab, ...indLatest.ba].map((r) => r.industry_descr)).size}</b>
                    </div>
                  </div>
                )}
                {inds.loading && !indLatest.ab.length ? (
                  <Skel h={300} />
                ) : (
                  <div className="tx-two">
                    {[
                      ["AB", indLatest.ab, p.A, `${aName} → ${bName}`],
                      ["BA", indLatest.ba, p.B, `${bName} → ${aName}`],
                    ].map(([k, rows, color, title]) => {
                      const tot = rows.reduce((s, r) => s + r.usd_m, 0);
                      return (
                        <div key={k}>
                          <div className="tx-colhead">
                            <span className="tx-dot" style={{ background: color }} />
                            {title}
                          </div>
                          {rows.length ? (
                            <BarList
                              color={color}
                              rows={rows.slice(0, 10).map((r) => ({
                                key: r.industry_descr,
                                label: cleanIndustry(r.industry_descr),
                                value: r.usd_m,
                                display: fmtUSD(r.usd_m),
                                meta: tot > 0 ? fmtPct(r.usd_m / tot, 0) : null,
                              }))}
                              onPick={(r) => IND.set(filters.oneOf(r.key))}
                              pickHint={(r) => `Filter the page to ${r.label}`}
                            />
                          ) : (
                            <Empty />
                          )}
                        </div>
                      );
                    })}
                  </div>
                )}
                <Explain title="Grubel–Lloyd index:">
                  0 means the two countries trade completely different products (inter-industry trade, as in comparative-advantage
                  models); 1 means they exchange the same kinds of products in both directions (intra-industry trade, typical between
                  similar rich economies — think cars for cars).
                </Explain>
              </Card>

              <Card w={12} title="How the mix has changed" sub="Each direction's exports split by broad sector (share of the year's total).">
                <Legend items={SECTORS.map((s) => ({ label: s, color: p.sectors[s], square: true }))} />
                <div className="tx-two">
                  {[
                    ["AB", `${aName} → ${bName}`, p.A],
                    ["BA", `${bName} → ${aName}`, p.B],
                  ].map(([k, title, color]) => {
                    const rows = sectorRows(k);
                    return (
                      <div key={k}>
                        <div className="tx-colhead">
                          <span className="tx-dot" style={{ background: color }} />
                          {title}
                        </div>
                        {sectors.loading && !rows.length ? <Skel h={190} /> : rows.length ? <VegaChart spec={mixSpec} data={rows} /> : <Empty />}
                      </div>
                    );
                  })}
                </div>
                <Explain title="Coverage note:">
                  ITPD-E covers agriculture from 1986, manufacturing and mining & energy from 1988, and services from 2000 — so mixes
                  before 2000 show goods only.
                </Explain>
              </Card>
            </div>
          </>
        )}
      </main>
    </>
  );

}


// ── Country Trade Profile ────────────────────────────────────────────────────
const TRY_COUNTRIES = ["Germany", "China", "Mexico", "Vietnam", "Nigeria", "Chile", "India", "Australia", "Korea, South"];

// Ordinary least squares for y = a + b1·x1 + b2·x2 (normal equations, 3×3 solve).
function ols2(rows) {
  const n = rows.length;
  if (n < 8) return null;
  const S = [[0, 0, 0], [0, 0, 0], [0, 0, 0]];
  const t = [0, 0, 0];
  for (const r of rows) {
    const x = [1, r.x1, r.x2];
    for (let i = 0; i < 3; i++) {
      t[i] += x[i] * r.y;
      for (let j = 0; j < 3; j++) S[i][j] += x[i] * x[j];
    }
  }
  // Gaussian elimination
  const M = S.map((row, i) => [...row, t[i]]);
  for (let c = 0; c < 3; c++) {
    let piv = c;
    for (let r = c + 1; r < 3; r++) if (Math.abs(M[r][c]) > Math.abs(M[piv][c])) piv = r;
    [M[c], M[piv]] = [M[piv], M[c]];
    if (Math.abs(M[c][c]) < 1e-12) return null;
    for (let r = 0; r < 3; r++) {
      if (r === c) continue;
      const f = M[r][c] / M[c][c];
      for (let k = c; k < 4; k++) M[r][k] -= f * M[c][k];
    }
  }
  const beta = M.map((row, i) => row[3] / row[i]);
  const ybar = rows.reduce((s, r) => s + r.y, 0) / n;
  let ssr = 0,
    sst = 0;
  for (const r of rows) {
    const yh = beta[0] + beta[1] * r.x1 + beta[2] * r.x2;
    ssr += (r.y - yh) ** 2;
    sst += (r.y - ybar) ** 2;
  }
  return { a: beta[0], bGdp: beta[1], bDist: beta[2], r2: sst > 0 ? 1 - ssr / sst : null, n };
}

// ── Trade with partners over time (One country tab) ──────────────────────────
// Lines for a group of partners: top 10 / 11–20 / 21–30 overall, or the top 10
// within a UN region. One hue for all lines (10 series is too many to tell apart
// by color); the hovered partner is highlighted, others fade, and every line
// carries a name label at its end. The side list doubles as a legend: hover a
// name to highlight its line, click it to open Two countries for the pair.
const PT_GROUPS = [
  { id: "top10", label: "Top 10", lo: 0, hi: 10 },
  { id: "top20", label: "11–20", lo: 10, hi: 20 },
  { id: "top30", label: "21–30", lo: 20, hi: 30 },
];
const PT_REGIONS = ["Africa", "Americas", "Asia", "Europe", "Oceania"];
const PT_MEASURES = [
  { id: "total", label: "Two-way trade", pick: (r) => (r.exports_m || 0) + (r.imports_m || 0), tot: (t) => (t.exports_m || 0) + (t.imports_m || 0) },
  { id: "exports", label: "Exports", pick: (r) => r.exports_m || 0, tot: (t) => t.exports_m || 0 },
  { id: "imports", label: "Imports", pick: (r) => r.imports_m || 0, tot: (t) => t.imports_m || 0 },
];

const PT_CSS = `
.pt-bar{display:flex;flex-wrap:wrap;gap:8px 18px;align-items:center;margin:2px 0 12px}
.pt-seg{display:inline-flex;border:1px solid var(--line);border-radius:999px;padding:2px;gap:2px;background:var(--card)}
.pt-seg button{font:inherit;font-size:12.5px;border:0;background:transparent;color:var(--ink2);padding:5px 11px;border-radius:999px;cursor:pointer;white-space:nowrap}
.pt-seg button:hover{color:var(--ink);background:var(--chip)}
.pt-seg button.on{background:var(--dash-accent);color:#fff;font-weight:600}
.pt-lbl{font-size:11px;font-weight:650;letter-spacing:.06em;text-transform:uppercase;color:var(--muted);margin-right:2px}
.pt-wrap{display:grid;grid-template-columns:minmax(0,1fr) 270px;gap:18px;align-items:start}
@media (max-width:900px){.pt-wrap{grid-template-columns:1fr}}
.pt-list{display:flex;flex-direction:column;gap:2px}
.pt-row{display:grid;grid-template-columns:20px minmax(0,1fr) auto auto;gap:8px;align-items:center;padding:6px 8px;border-radius:9px;cursor:pointer}
.pt-row:hover,.pt-row.hl{background:var(--chip)}
.pt-row .rk{font-size:11.5px;color:var(--muted);font-variant-numeric:tabular-nums}
.pt-row .nm{font-size:13.2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.pt-row .vl{font-size:13px;font-weight:650;font-variant-numeric:tabular-nums;text-align:right}
.pt-row .sh{font-size:11.5px;color:var(--muted);font-variant-numeric:tabular-nums;min-width:40px;text-align:right}
.pt-note{font-size:11.5px;color:var(--muted);padding:6px 8px 0}
`;

function PartnerTrends({ rows, totals, name, p, onCompare, loading }) {
  const [group, setGroup] = useUrlState("cpg", "top10");
  const [measure, setMeasure] = useUrlState("cpm", "total");
  const [scale, setScale] = useUrlState("cps", "usd");
  const [hl, setHl] = useState("");
  const M = PT_MEASURES.find((m) => m.id === measure) || PT_MEASURES[0];
  const share = scale === "share";

  const latest = latestYear(rows);
  const first = firstYear(rows);
  const totByYear = useMemo(() => new Map(totals.map((t) => [t.year, M.tot(t)])), [totals, M]);

  // Rank partners by the chosen measure in the latest year, then pick the group.
  const chosen = useMemo(() => {
    const now = rows.filter((r) => r.year === latest && M.pick(r) > 0);
    const pool = PT_REGIONS.includes(group) ? now.filter((r) => r.partner_region === group) : now;
    const ranked = pool.sort((a, b) => M.pick(b) - M.pick(a));
    const g = PT_GROUPS.find((x) => x.id === group);
    const slice = g ? ranked.slice(g.lo, g.hi) : ranked.slice(0, 10);
    const offset = g ? g.lo : 0;
    const tot = totByYear.get(latest) || 0;
    return slice.map((r, i) => ({ partner: r.partner, region: r.partner_region, rank: offset + i + 1, value: M.pick(r), sh: tot > 0 ? M.pick(r) / tot : null }));
  }, [rows, latest, group, M, totByYear]);

  const data = useMemo(() => {
    const set = new Map(chosen.map((c) => [c.partner, c.rank]));
    const out = [];
    for (const r of rows) {
      if (!set.has(r.partner)) continue;
      const v = M.pick(r);
      const tot = totByYear.get(r.year) || 0;
      out.push({
        year: r.year, partner: r.partner, rank: set.get(r.partner),
        v: share ? (tot > 0 ? v / tot : null) : v / 1000,
        hl: hl === r.partner, anyhl: !!hl,
      });
    }
    const clean = out.filter((d) => d.v != null).sort((a, b) => a.rank - b.rank || a.year - b.year);
    // End labels: one per partner at its last year, nudged apart so names never overlap.
    const last = new Map();
    for (const d of clean) if (!last.has(d.partner) || d.year > last.get(d.partner).year) last.set(d.partner, d);
    const ends = [...last.values()].sort((a, b) => b.v - a.v);
    const maxV = Math.max(...clean.map((d) => d.v), 0);
    const gap = maxV * 0.05;
    let prev = Infinity;
    for (const e of ends) {
      e.labelV = Math.min(e.v, prev - gap);
      prev = e.labelV;
    }
    return clean;
  }, [rows, chosen, M, share, hl, totByYear]);

  const spec = useMemo(() => {
    const valueTxt = share ? "format(datum.v, '.1%')" : bnText("v");
    const flip = latest && first ? (first + latest) / 2 : 2012;
    const on = (v, off) => ({ condition: [{ param: "lp", empty: false, value: v }, { test: "datum.hl", value: v }], value: off });
    return {
      height: 400,
      config: vegaConfig(p),
      encoding: {
        x: { field: "year", type: "quantitative", title: null, axis: { format: "d", tickMinStep: 1 }, scale: { nice: false } },
        y: { field: "v", type: "quantitative", title: null, axis: share ? { format: ".0%" } : { labelExpr: BN_LABEL } },
      },
      layer: [
        {
          mark: { type: "line", interpolate: "monotone", strokeCap: "round" },
          encoding: {
            detail: { field: "partner" },
            color: on(p.B, p.A),
            strokeWidth: on(3.5, 1.8),
            opacity: { condition: [{ param: "lp", empty: false, value: 1 }, { test: "datum.hl", value: 1 }], value: { expr: "length(data('lp_store')) || datum.anyhl ? 0.18 : 0.7" } },
          },
        },
        {
          // Invisible hit targets: the nearest point picks the partner (and year).
          params: [
            { name: "lp", select: { type: "point", fields: ["partner"], nearest: true, on: "pointermove", clear: "pointerout" } },
            { name: "ly", select: { type: "point", fields: ["partner", "year"], nearest: true, on: "pointermove", clear: "pointerout" } },
          ],
          mark: { type: "point", opacity: 0, size: 100 },
        },
        {
          transform: [{ filter: { param: "ly", empty: false } }],
          mark: { type: "point", filled: true, size: 80, color: p.B, stroke: p.surface, strokeWidth: 2 },
        },
        // End-of-line name labels (latest year).
        {
          transform: [{ filter: "isValid(datum.labelV)" }],
          mark: { type: "text", align: "left", dx: 6, fontSize: 11, clip: false },
          encoding: {
            y: { field: "labelV", type: "quantitative" },
            text: { field: "partner" },
            color: on(p.ink, p.ink2),
            fontWeight: { condition: [{ param: "lp", empty: false, value: 700 }, { test: "datum.hl", value: 700 }], value: 500 },
            opacity: { condition: [{ param: "lp", empty: false, value: 1 }, { test: "datum.hl", value: 1 }], value: { expr: "length(data('lp_store')) || datum.anyhl ? 0.35 : 0.9" } },
          },
        },
        // Hover readout: "Canada · $348B · 2023" (a halo pass, then the text).
        ...[{ stroke: p.surface, strokeWidth: 5, strokeJoin: "round" }, {}].map((halo) => ({
          transform: [{ filter: { param: "ly", empty: false } }, { calculate: `datum.partner + ' · ' + ${valueTxt} + ' · ' + datum.year`, as: "txt" }],
          mark: {
            type: "text", dy: -14, fontSize: 13, fontWeight: 700, color: p.ink, clip: true, ...halo,
            align: { expr: `datum.year > ${flip} ? 'right' : 'left'` },
            dx: { expr: `datum.year > ${flip} ? -10 : 10` },
          },
          encoding: { text: { field: "txt" } },
        })),
      ],
    };
  }, [p, share, latest, first]);

  const groupLabel = PT_REGIONS.includes(group)
    ? `top 10 partners in ${group}`
    : group === "top10" ? "top 10 partners" : `partners ranked ${(PT_GROUPS.find((g) => g.id === group) || PT_GROUPS[0]).label}`;
  const seg = (items, value, set) => (
    <div className="pt-seg">
      {items.map((it) => (
        <button key={it.id} className={value === it.id ? "on" : ""} onClick={() => set(it.id)} aria-pressed={value === it.id}>
          {it.label}
        </button>
      ))}
    </div>
  );

  return (
    <>
      <style>{PT_CSS}</style>
      <div className="pt-bar">
        <span>
          <span className="pt-lbl">Partners</span> {seg(PT_GROUPS, group, setGroup)}
        </span>
        <span>
          <span className="pt-lbl">Region</span> {seg(PT_REGIONS.map((r) => ({ id: r, label: r })), group, setGroup)}
        </span>
        <span>
          <span className="pt-lbl">Measure</span> {seg(PT_MEASURES, measure, setMeasure)}
        </span>
        <span>
          <span className="pt-lbl">Show</span> {seg([{ id: "usd", label: "$ billions" }, { id: "share", label: `% of ${name}'s total` }], scale, setScale)}
        </span>
      </div>
      {loading && !rows.length ? (
        <Skel h={380} />
      ) : !chosen.length ? (
        <Empty>No partners with trade in this group for the selected years and filters.</Empty>
      ) : (
        <div className="pt-wrap">
          <div onMouseLeave={() => setHl("")}>
            <VegaChart spec={spec} data={data} />
          </div>
          <div className="pt-list" onMouseLeave={() => setHl("")}>
            {chosen.map((c) => (
              <div
                key={c.partner}
                className={`pt-row${hl === c.partner ? " hl" : ""}`}
                onMouseEnter={() => setHl(c.partner)}
                onClick={() => onCompare(name, c.partner)}
                title={`Compare ${name} and ${c.partner} in Two countries`}
              >
                <span className="rk">{c.rank}</span>
                <span className="nm" title={c.region}>
                  {c.partner}
                </span>
                <span className="vl">{fmtUSD(c.value)}</span>
                <span className="sh">{c.sh != null ? fmtPct(c.sh) : ""}</span>
              </div>
            ))}
            <div className="pt-note">
              {M.label} in {latest}, and share of {name}'s total. Click a name to compare the two countries.
            </div>
          </div>
        </div>
      )}
      <Explain title="How to use this:">
        Lines show {M.label.toLowerCase()} with {name}'s {groupLabel} (by {M.label.toLowerCase()} in {latest}). Point at a line (or a name on
        the right) to highlight it; click a name to see what the two countries trade. Switch to <b>% of total</b> to see which
        partners are gaining or losing ground rather than just growing with world trade.
      </Explain>
    </>
  );
}

const C_KEYS = ['COUNTRY', 'C_SECTOR', 'C_INDUSTRY', 'C_YEAR_RANGE'];

function CountryTab({ givens: allGivens, onCompare }) {
  const givens = useMemo(() => pickGivens(allGivens, C_KEYS), [JSON.stringify(pickGivens(allGivens, C_KEYS))]);
  const p = usePalette();
  const C = useGiven("COUNTRY");
  const IND = useGiven("C_INDUSTRY");
  const name = pickedValue(C.value) || "Country";
  const industry = cleanIndustry(pickedValue(givens.C_INDUSTRY));
  const sector = pickedValue(givens.C_SECTOR);
  const selection = industry || sector || "all goods & services";

  const totals = useRows("c_totals_by_year", givens);
  const regions = useRows("c_exports_by_region_year", givens);
  const partnersQ = useRows("c_partners_by_year", givens);
  const indsQ = useRows("c_industries_by_year", givens);
  const partners = useMemo(() => ({ loading: partnersQ.loading, rows: unnest(partnersQ.rows, "partners") }), [partnersQ.rows, partnersQ.loading]);
  const inds = useMemo(() => ({ loading: indsQ.loading, rows: unnest(indsQ.rows, "industries") }), [indsQ.rows, indsQ.loading]);
  const facts = useRows("c_country_facts", givens);
  const f = facts.rows[0];

  const T = totals.rows;
  const L = T.length ? T[T.length - 1] : null;
  const F = T.find((r) => r.exports_m > 0) || null;
  const grow = L && F && L.year > F.year ? cagr(F.exports_m, L.exports_m, L.year - F.year) : null;
  const balance = L ? L.exports_m - L.imports_m : null;
  // ITPD-E R2025 production (domestic sales) data is complete only through 2021;
  // 2022 is partial and 2023 nearly empty, so the openness ratio uses year ≤ 2021.
  const D = [...T].reverse().find((r) => r.year <= 2021 && r.domestic_m > 0) || null;
  const openness = D ? D.exports_m / (D.exports_m + D.domestic_m) : null;

  const lineRows = useMemo(
    () => T.flatMap((r) => [{ year: r.year, key: "X", v: r.exports_m / 1000 }, { year: r.year, key: "M", v: r.imports_m / 1000 }]),
    [T],
  );
  const regionRows = useMemo(() => regions.rows.map((r) => ({ year: r.year, region: r.region, so: REGIONS.indexOf(r.region), v: r.usd_m / 1000 })), [regions.rows]);

  const py = latestYear(partners.rows);
  const pFirst = firstYear(partners.rows);
  const partnersLatest = useMemo(() => partners.rows.filter((r) => r.year === py), [partners.rows, py]);
  const earlyShare = useMemo(() => {
    const rows = partners.rows.filter((r) => r.year === pFirst);
    const tx = rows.reduce((s, r) => s + (r.exports_m || 0), 0);
    const tm = rows.reduce((s, r) => s + (r.imports_m || 0), 0);
    const m = new Map(rows.map((r) => [r.partner, { x: tx > 0 ? r.exports_m / tx : 0, m: tm > 0 ? r.imports_m / tm : 0 }]));
    return m;
  }, [partners.rows, pFirst]);
  const topList = (field) => {
    const tot = partnersLatest.reduce((s, r) => s + (r[field] || 0), 0);
    return partnersLatest
      .filter((r) => r[field] > 0)
      .sort((a, b) => b[field] - a[field])
      .slice(0, 12)
      .map((r) => {
        const sh = tot > 0 ? r[field] / tot : 0;
        const was = earlyShare.get(r.partner)?.[field === "exports_m" ? "x" : "m"];
        const arrow = was == null || py === pFirst ? "" : sh > was + 0.0005 ? ` ▲ from ${fmtPct(was, 0)}` : sh < was - 0.0005 ? ` ▼ from ${fmtPct(was, 0)}` : "";
        return {
          key: r.partner,
          label: r.partner,
          value: r[field],
          display: fmtUSD(r[field]),
          meta: `${fmtPct(sh, 1)}${arrow}`,
          tag: r.partner_region,
          color: p.regions[r.partner_region] || p.regions.Other,
        };
      });
  };

  // Gravity scatter: latest year ≤ 2019 that has distance + GDP data.
  const gYear = useMemo(() => {
    let y = null;
    for (const r of partners.rows) if (r.year <= 2019 && r.distance_km > 0 && r.partner_gdp_bn > 0 && (y == null || r.year > y)) y = r.year;
    return y;
  }, [partners.rows]);
  const gRows = useMemo(
    () =>
      partners.rows
        .filter((r) => r.year === gYear && r.exports_m > 0.05 && r.distance_km > 0 && r.partner_gdp_bn > 0)
        .map((r) => ({ partner: r.partner, x: r.distance_km, y: r.exports_m, gdp: r.partner_gdp_bn, region: r.partner_region || "Other" }))
        .sort((a, b) => b.y - a.y)
        .map((r, i) => ({ ...r, rank: i + 1 })),
    [partners.rows, gYear],
  );
  const fit = useMemo(() => ols2(gRows.map((r) => ({ y: Math.log(r.y), x1: Math.log(r.gdp), x2: Math.log(r.x) }))), [gRows]);
  // Simple power-law fit of exports on distance (log-log OLS) for the grey trend line.
  const gData = useMemo(() => {
    const pts = gRows.map((r) => ({ ...r, kind: "pt" }));
    if (gRows.length < 3) return pts;
    const lx = gRows.map((r) => Math.log(r.x));
    const ly = gRows.map((r) => Math.log(r.y));
    const mx = lx.reduce((a, b) => a + b, 0) / lx.length;
    const my = ly.reduce((a, b) => a + b, 0) / ly.length;
    let sxy = 0, sxx = 0;
    lx.forEach((x, i) => { sxy += (x - mx) * (ly[i] - my); sxx += (x - mx) ** 2; });
    const b = sxx > 0 ? sxy / sxx : 0;
    const a = my - b * mx;
    const lo = Math.min(...lx), hi = Math.max(...lx);
    const line = [0, 1].map((t) => {
      const x = Math.exp(lo + t * (hi - lo));
      return { kind: "fit", x, y: Math.exp(a + b * Math.log(x)) };
    });
    return [...pts, ...line];
  }, [gRows]);

  const indLatestYear = latestYear(inds.rows);
  const indRows = inds.rows.filter((r) => r.year === indLatestYear);
  const indList = (field, color) => {
    const tot = indRows.reduce((s, r) => s + (r[field] || 0), 0);
    return indRows
      .filter((r) => r[field] > 0)
      .sort((a, b) => b[field] - a[field])
      .slice(0, 10)
      .map((r) => ({
        key: r.industry_descr,
        label: cleanIndustry(r.industry_descr),
        value: r[field],
        display: fmtUSD(r[field]),
        meta: tot > 0 ? fmtPct(r[field] / tot, 0) : null,
        tag: r.broad_sector,
        color,
      }));
  };

  const lspec = useMemo(
    () => lineSpec({ p, keys: ["X", "M"], colors: [p.A, p.B], yTitle: null, yFormat: BN_LABEL, valueText: bnText("v"), height: 300 }),
    [p],
  );
  const regSpec = useMemo(
    () => ({
      height: 250,
      config: vegaConfig(p),
      mark: { type: "bar", width: { band: 0.8 }, stroke: p.surface, strokeWidth: 1 },
      encoding: {
        x: { field: "year", type: "ordinal", title: null, axis: { labelAngle: 0, labelExpr: "datum.value % 5 == 0 ? datum.value : ''" } },
        y: { field: "v", type: "quantitative", stack: "normalize", title: null, axis: { format: ".0%" } },
        color: { field: "region", type: "nominal", scale: { domain: REGIONS, range: REGIONS.map((r) => p.regions[r]) }, legend: null },
        order: { field: "so", type: "quantitative", sort: "ascending" },
        tooltip: [
          { field: "year", type: "ordinal", title: "Year" },
          { field: "region", type: "nominal", title: "Destination region" },
          { field: "v", type: "quantitative", title: "Exports ($ billions)", format: ",.2f" },
        ],
      },
    }),
    [p],
  );
  const gSpec = useMemo(
    () => ({
      height: 340,
      config: vegaConfig(p),
      layer: [
        {
          mark: { type: "line", color: p.muted, strokeWidth: 1.5, opacity: 0.8 },
          transform: [{ filter: "datum.kind === 'fit'" }],
          encoding: {
            x: { field: "x", type: "quantitative", scale: { type: "log" } },
            y: { field: "y", type: "quantitative", scale: { type: "log" } },
          },
        },
        {
          transform: [{ filter: "datum.kind === 'pt' && datum.rank <= 8" }],
          mark: { type: "text", align: "left", dx: 7, dy: -7, fontSize: 11.5, fontWeight: 600, color: p.ink2 },
          encoding: {
            x: { field: "x", type: "quantitative", scale: { type: "log" } },
            y: { field: "y", type: "quantitative", scale: { type: "log" } },
            text: { field: "partner" },
          },
        },
        {
          // Circles + their hover label share one layer so the hover selection is in scope.
          transform: [
            { filter: "datum.kind === 'pt'" },
            { calculate: "datum.partner + ' · $' + (datum.y >= 10000 ? format(datum.y / 1000, ',.0f') : datum.y >= 100 ? format(datum.y / 1000, ',.1f') : format(datum.y / 1000, ',.2f')) + 'B exports'", as: "hoverTxt" },
          ],
          encoding: {
            x: { field: "x", type: "quantitative", scale: { type: "log", nice: false }, title: "Distance to partner (km, log scale)", axis: { tickCount: 6, format: "~s" } },
            y: {
              field: "y", type: "quantitative", scale: { type: "log" }, title: "Exports to partner (log scale)",
              axis: { labelExpr: "datum.value >= 1e6 ? '$' + format(datum.value/1e6, '~g') + 'T' : datum.value >= 1000 ? '$' + format(datum.value/1000, '~g') + 'B' : datum.value >= 1 ? '$' + format(datum.value, '~g') + 'M' : '$' + format(datum.value*1000, '~g') + 'K'" },
            },
          },
          layer: [
            {
              params: [{ name: "gh", select: { type: "point", fields: ["partner"], nearest: true, on: "pointermove", clear: "pointerout" } }],
              mark: { type: "circle", cursor: "pointer" },
              encoding: {
                size: { field: "gdp", type: "quantitative", scale: { type: "sqrt", range: [16, 900] }, legend: null },
                color: { value: p.A },
                opacity: { condition: { param: "gh", empty: true, value: 0.78 }, value: 0.35 },
                stroke: { condition: { param: "gh", empty: false, value: p.ink }, value: p.surface },
                strokeWidth: { condition: { param: "gh", empty: false, value: 2 }, value: 1.5 },
              },
            },
            // Hover label: partner name and exports in billions (a halo pass, then the text).
            ...[{ stroke: p.surface, strokeWidth: 5, strokeJoin: "round" }, {}].map((halo) => ({
              mark: {
                type: "text", dy: -12, fontSize: 13, fontWeight: 700, color: p.ink, clip: true, ...halo,
                // Label to the right of the circle, or to the left near the right edge.
                align: { expr: "datum.x > 9000 ? 'right' : 'left'" },
                dx: { expr: "datum.x > 9000 ? -12 : 12" },
              },
              encoding: {
                text: { field: "hoverTxt" },
                opacity: { condition: { param: "gh", empty: false, value: 1 }, value: 0 },
              },
            })),
          ],
        },
      ],
    }),
    [p],
  );

  const setCountry = (n) => C.set(filters.oneOf(n));
  const groups = f ? [f.ldc && "Least developed country", f.lldc && "Landlocked developing", f.sids && "Small island developing state"].filter(Boolean) : [];

  return (
    <>
      <Hero
        eyebrow="International trade · country profile"
        title={name}
        sub="Where does a country sell, and who does it buy from? Follow its exports and imports over time, see which regions and partners matter most, and test the gravity model against its trading partners."
      >
        <div className="tx-controls">
          <GivenSelect given="COUNTRY" label="Country" dot={p.A} />
          <SectorIndustry prefix="C" />
          <YearRange prefix="C" />
        </div>
        <div className="tx-try">
          Try:
          {TRY_COUNTRIES.map((c) => (
            <button key={c} onClick={() => setCountry(c)}>
              {c}
            </button>
          ))}
        </div>
        <div className="tx-chips">
          {f && <span className="tx-chip">{[f.sub_region, f.region].filter(Boolean).join(", ") || "No UN region"}</span>}
          {f?.wb_income_group_current && <span className="tx-chip">World Bank: {f.wb_income_group_current}</span>}
          {groups.map((g) => (
            <span className="tx-chip" key={g}>
              {g}
            </span>
          ))}
          <span className="tx-chip">Showing: {selection}</span>
        </div>
      </Hero>

      <main className="tx-body">
        <div className="tx-kpis">
          <Kpi accent={p.A} dot={p.A} label="Exports" value={L ? fmtUSD(L.exports_m) : "–"} sub={L ? <>in {L.year} · {grow != null && <Delta value={grow} suffix="/yr" />} since {F.year}</> : totals.loading ? "loading…" : "no data"} />
          <Kpi accent={p.B} dot={p.B} label="Imports" value={L ? fmtUSD(L.imports_m) : "–"} sub={L ? `in ${L.year}` : ""} />
          <Kpi
            label="Trade balance"
            value={balance == null ? "–" : `${balance >= 0 ? "+" : ""}${fmtUSD(balance)}`}
            sub={balance == null ? "" : balance >= 0 ? "surplus (exports > imports)" : "deficit (imports > exports)"}
          />
          <Kpi label="Export destinations" value={L ? fmtNum(L.export_partners) : "–"} sub={L ? `countries buying in ${L.year}` : ""} />
          <Kpi
            label="Share of output exported"
            value={openness == null ? "–" : fmtPct(openness)}
            sub={D ? `exports ÷ (exports + home sales), ${D.year} · overstated where home-sales data is incomplete` : "production data ends in 2021"}
          />
        </div>

        <div className="tx-grid">
          <Card w={7} title="Exports and imports over time" sub={`Current US dollars · ${selection}. Hover to read values.`}>
            <Legend items={[{ label: "Exports", color: p.A }, { label: "Imports", color: p.B }]} />
            {totals.loading && !lineRows.length ? <Skel h={300} /> : lineRows.length ? <VegaChart spec={lspec} data={lineRows} /> : <Empty />}
            <Explain title="Reading the gap:">
              when the blue line is above the orange one the country runs a trade surplus; below it, a deficit. Watch for the
              2009 financial crisis and the 2020 pandemic — trade falls faster than GDP in downturns.
            </Explain>
          </Card>
          <Card w={5} title="Where do exports go?" sub="Share of exports by destination region, each year. Hover a segment for values.">
            <Legend items={REGIONS.map((r) => ({ label: r, color: p.regions[r], square: true }))} />
            {regions.loading && !regionRows.length ? <Skel h={250} /> : regionRows.length ? <VegaChart spec={regSpec} data={regionRows} /> : <Empty />}
          </Card>

          <Card w={6} title={`Top export destinations${py ? ` (${py})` : ""}`} sub={`Share of ${name}'s exports, with the change since ${pFirst ?? "the first year"}. Click a country to see what the two trade.`}>
            {partners.loading && !partnersLatest.length ? (
              <Skel h={380} />
            ) : partnersLatest.length ? (
              <BarList rows={topList("exports_m")} onPick={(r) => onCompare(name, r.key)} pickHint={(r) => `Compare ${name} and ${r.label} in Two countries`} />
            ) : (
              <Empty />
            )}
          </Card>
          <Card w={6} title={`Top import sources${py ? ` (${py})` : ""}`} sub={`Share of ${name}'s imports, with the change since ${pFirst ?? "the first year"}. Click a country to see what the two trade.`}>
            {partners.loading && !partnersLatest.length ? (
              <Skel h={380} />
            ) : partnersLatest.length ? (
              <BarList rows={topList("imports_m")} onPick={(r) => onCompare(name, r.key)} pickHint={(r) => `Compare ${name} and ${r.label} in Two countries`} />
            ) : (
              <Empty />
            )}
          </Card>

          <Card
            w={12}
            title={`Trade with partners over time`}
            sub={`How ${name}'s trade with its main partners has evolved · ${selection}. Pick a group of partners, a region, or a measure.`}
          >
            <PartnerTrends rows={partners.rows} totals={T} name={name} p={p} onCompare={onCompare} loading={partners.loading} />
          </Card>

          <Card
            w={12}
            title={`The gravity model, live${gYear ? ` (${gYear})` : ""}`}
            sub={`Each circle is a country that buys from ${name}; circle size = the partner's GDP. Point at a circle for its name and value. The grey line is the best power-law fit of exports on distance.`}
          >
            {fit && (
              <div className="tx-stat">
                <div>
                  Distance elasticity
                  <b>{fit.bDist.toFixed(2)}</b>
                </div>
                <div>
                  Partner-size (GDP) elasticity
                  <b>{fit.bGdp.toFixed(2)}</b>
                </div>
                <div>
                  R² (fit)
                  <b>{fit.r2 != null ? fit.r2.toFixed(2) : "–"}</b>
                </div>
                <div>
                  Partners in fit
                  <b>{fit.n}</b>
                </div>
              </div>
            )}
            {partners.loading && !gRows.length ? <Skel h={340} /> : gRows.length ? <VegaChart spec={gSpec} data={gData} /> : <Empty>Gravity variables cover 1986–2019 — widen the year range to include those years.</Empty>}
            <Explain title="How to read the elasticities:">
              they come from a regression of log exports on log partner GDP and log distance across all of {name}'s partners in one
              year. A distance elasticity of −1 means a partner twice as far away buys about half as much, holding size fixed; a GDP
              elasticity near +1 means exports grow in proportion to the partner's economy — the core predictions of the gravity model.
            </Explain>
          </Card>

          <Card w={6} title={`What does ${name} export?${indLatestYear ? ` (${indLatestYear})` : ""}`} sub="Top industries by export value. Click one to filter the page to it.">
            {inds.loading && !indRows.length ? <Skel h={330} /> : indRows.length ? <BarList rows={indList("exports_m", p.A)} onPick={(r) => IND.set(filters.oneOf(r.key))} pickHint={(r) => `Filter to ${r.label}`} /> : <Empty />}
          </Card>
          <Card w={6} title={`What does ${name} import?${indLatestYear ? ` (${indLatestYear})` : ""}`} sub="Top industries by import value. Click one to filter the page to it.">
            {inds.loading && !indRows.length ? <Skel h={330} /> : indRows.length ? <BarList rows={indList("imports_m", p.B)} onPick={(r) => IND.set(filters.oneOf(r.key))} pickHint={(r) => `Filter to ${r.label}`} /> : <Empty />}
          </Card>
        </div>
      </main>
    </>
  );
}

// ── World Trade at a Glance ──────────────────────────────────────────────────
const STORIES = [
  { label: "Full history (1988–2023, goods only before 2000)", range: [1988, 2023] },
  { label: "China joins the WTO (1995–2010)", range: [1995, 2010] },
  { label: "The Great Trade Collapse (2005–2012)", range: [2005, 2012] },
  { label: "Pandemic & recovery (2017–2023)", range: [2017, 2023] },
];
const INCOME = ["Low income", "Lower middle income", "Upper middle income", "High income"];
const INCOME_RAMP = { light: ["#86b6ef", "#3987e5", "#1c5cab", "#0d366b"], dark: ["#184f95", "#2a78d6", "#6da7ec", "#b7d3f6"] };
const EVENTS = [
  { year: 2009, text: "Global financial crisis" },
  { year: 2020, text: "COVID-19" },
];

const W_KEYS = ['W_SECTOR', 'W_INDUSTRY', 'W_YEAR_RANGE'];

function WorldTab({ givens: allGivens }) {
  const givens = useMemo(() => pickGivens(allGivens, W_KEYS), [JSON.stringify(pickGivens(allGivens, W_KEYS))]);
  const p = usePalette();
  const dark = useDark();
  const YR = useGiven("W_YEAR_RANGE");
  const industry = cleanIndustry(pickedValue(givens.W_INDUSTRY));
  const sector = pickedValue(givens.W_SECTOR);
  const selection = industry || sector || "all goods & services";

  const sectors = useRows("w_sectors_by_year", givens);
  const structure = useRows("w_structure_by_year", givens);
  const flows = useRows("w_region_flows_by_year", givens);
  const expQ = useRows("w_exporters_by_year", givens);
  const income = useRows("w_income_by_year", givens);
  const exporters = useMemo(() => unnest(expQ.rows, "exporters"), [expQ.rows]);

  const S = structure.rows;
  const L = S.length ? S[S.length - 1] : null;
  const F = S.length ? S[0] : null;
  const grow = L && F && L.year > F.year ? cagr(F.usd_m, L.usd_m, L.year - F.year) : null;
  const P = [...S].reverse().find((r) => r.year <= 2019 && r.pta_trade_share != null) || null;

  const sectorRows = useMemo(() => sectors.rows.map((r) => ({ year: r.year, sector: r.broad_sector, so: SECTORS.indexOf(r.broad_sector), v: r.usd_m / 1000 })), [sectors.rows]);
  const yearsShown = new Set(sectorRows.map((r) => r.year));
  const events = EVENTS.filter((e) => yearsShown.has(e.year));

  const ey = latestYear(exporters);
  const ef = firstYear(exporters);
  const leaders = useMemo(() => {
    const rankAt = (y) => {
      const m = new Map();
      exporters
        .filter((r) => r.year === y)
        .sort((a, b) => b.usd_m - a.usd_m)
        .forEach((r, i) => m.set(r.country, i + 1));
      return m;
    };
    const then = rankAt(ef);
    const now = exporters.filter((r) => r.year === ey).sort((a, b) => b.usd_m - a.usd_m);
    const tot = now.reduce((s, r) => s + r.usd_m, 0);
    return now.slice(0, 12).map((r, i) => {
      const was = then.get(r.country);
      return {
        key: r.country,
        label: `${i + 1}. ${r.country}`,
        value: r.usd_m,
        display: fmtUSD(r.usd_m),
        meta: `${fmtPct(r.usd_m / tot, 1)}${ef !== ey ? (was ? ` · #${was} in ${ef}` : ` · new since ${ef}`) : ""}`,
        tag: r.region,
        color: p.regions[r.region] || p.regions.Other,
      };
    });
  }, [exporters, ey, ef, p]);

  const fy = latestYear(flows.rows);
  const matrix = useMemo(() => {
    const rows = flows.rows.filter((r) => r.year === fy && r.from_region !== "Other" && r.to_region !== "Other");
    const regs = REGIONS.filter((r) => r !== "Other");
    const get = (a, b) => rows.find((r) => r.from_region === a && r.to_region === b)?.usd_m || 0;
    const max = Math.max(...rows.map((r) => r.usd_m), 1);
    return { regs, get, max };
  }, [flows.rows, fy]);
  const heat = (v) => {
    const ramp = PAL.light.seq; // sequential blue, light → dark (cells carry their own text color)
    const t = Math.sqrt(v / matrix.max);
    const i = Math.min(ramp.length - 1, Math.floor(t * ramp.length));
    return { background: v > 0 ? ramp[i] : "transparent", color: i >= 3 ? "#fff" : "#0b0b0b" };
  };

  const shareRows = useMemo(
    () =>
      S.flatMap((r) => [
        { year: r.year, key: "R", v: r.intra_regional_share },
        ...(r.year <= 2019 && r.pta_trade_share != null ? [{ year: r.year, key: "P", v: r.pta_trade_share }] : []),
      ]).filter((r) => r.v != null),
    [S],
  );
  const distRows = useMemo(
    () => S.filter((r) => r.year <= 2019 && r.trade_weighted_distance_km).map((r) => ({ year: r.year, key: "D", v: r.trade_weighted_distance_km })),
    [S],
  );
  const incRows = useMemo(() => income.rows.map((r) => ({ year: r.year, group: r.income_group, v: r.usd_m / 1000 })), [income.rows]);

  const areaSpec = useMemo(
    () => ({
      height: 420,
      config: vegaConfig(p),
      encoding: { x: { field: "year", type: "quantitative", title: null, axis: { format: "d", tickMinStep: 1 }, scale: { nice: false } } },
      layer: [
        {
          mark: { type: "area", interpolate: "monotone", stroke: p.surface, strokeWidth: 1.5, opacity: 0.95 },
          encoding: {
            y: { field: "v", type: "quantitative", stack: "zero", title: null, axis: { labelExpr: BN_LABEL } },
            color: { field: "sector", type: "nominal", scale: { domain: SECTORS, range: SECTORS.map((s) => p.sectors[s]) }, legend: null },
            order: { field: "so", type: "quantitative", sort: "ascending" },
          },
        },
        ...events.map((e) => ({
          data: { values: [e] },
          layer: [
            { mark: { type: "rule", color: p.muted, strokeWidth: 1 }, encoding: { x: { datum: e.year } } },
            { mark: { type: "text", align: "left", dx: 5, y: 8, fontSize: 11.5, color: p.ink2, fontStyle: "italic" }, encoding: { x: { datum: e.year }, text: { value: e.text } } },
          ],
        })),
        {
          params: [{ name: "hw", select: { type: "point", fields: ["year"], nearest: true, on: "pointermove", clear: "pointerout" } }],
          mark: { type: "rule", color: p.ink2, strokeWidth: 1 },
          encoding: { opacity: { condition: { param: "hw", empty: false, value: 1 }, value: 0 } },
        },
        {
          transform: [
            { filter: { param: "hw", empty: false } },
            { aggregate: [{ op: "sum", field: "v", as: "total" }], groupby: ["year"] },
            { calculate: `datum.year + ' · ' + ${bnText("total")}`, as: "txt" },
          ],
          mark: { type: "text", align: "left", dx: 8, y: 22, fontWeight: 700, fontSize: 12.5, color: p.ink },
          encoding: { text: { field: "txt" } },
        },
      ],
    }),
    [p, events.map((e) => e.year).join()],
  );
  const shareSpec = useMemo(
    () => lineSpec({ p, keys: ["R", "P"], colors: [p.A, p.B], yTitle: null, height: 230, yFormat: "format(datum.value, '.0%')", valueText: "format(datum.v, '.1%')", yZero: false }),
    [p],
  );
  const distSpec = useMemo(
    () => lineSpec({ p, keys: ["D"], colors: [p.A], yTitle: null, height: 230, yFormat: "format(datum.value, ',') + ' km'", valueText: "format(datum.v, ',.0f') + ' km'", yZero: true }),
    [p],
  );
  const incSpec = useMemo(
    () => ({
      height: 230,
      config: vegaConfig(p),
      mark: { type: "bar", width: { band: 0.8 }, stroke: p.surface, strokeWidth: 1 },
      encoding: {
        x: { field: "year", type: "ordinal", title: null, axis: { labelAngle: 0, labelExpr: "datum.value % 5 == 0 ? datum.value : ''" } },
        y: { field: "v", type: "quantitative", stack: "normalize", title: null, axis: { format: ".0%" } },
        color: { field: "group", type: "ordinal", scale: { domain: INCOME, range: dark ? INCOME_RAMP.dark : INCOME_RAMP.light }, legend: null },
        order: { field: "rank", type: "quantitative" },
        tooltip: [
          { field: "year", type: "ordinal", title: "Year" },
          { field: "group", title: "Exporter income group" },
          { field: "v", type: "quantitative", title: "Exports ($ billions)", format: ",.1f" },
        ],
      },
    }),
    [p, dark],
  );

  const setRange = (lo, hi) => YR.set(filters.between(lo, hi));

  return (
    <>
      <Hero
        eyebrow="International trade · the big picture"
        title="World Trade at a Glance"
        sub="How much the world trades across borders, in what, between which regions — and how globalisation has ebbed and flowed since the late 1980s."
      >
        <div className="tx-controls">
          <SectorIndustry prefix="W" />
          <YearRange prefix="W" />
        </div>
        <div className="tx-try">
          Explore:
          {STORIES.map((s) => (
            <button key={s.label} onClick={() => setRange(...s.range)}>
              {s.label}
            </button>
          ))}
        </div>
        <div className="tx-chips">
          <span className="tx-chip">Showing: {selection}</span>
          <span className="tx-chip">Cross-border trade only (domestic sales excluded)</span>
        </div>
      </Hero>

      <main className="tx-body">
        <div className="tx-kpis">
          <Kpi accent={p.A} label="World cross-border trade" value={L ? fmtUSD(L.usd_m) : "–"} sub={L ? `in ${L.year}` : structure.loading ? "loading…" : "no data"} />
          <Kpi label="Growth" value={grow == null ? "–" : <Delta value={grow} suffix="/yr" />} sub={grow == null ? "" : `compound annual, ${F.year}–${L.year}`} />
          <Kpi label="Trade within the same region" value={L ? fmtPct(L.intra_regional_share) : "–"} sub={L ? `of cross-border trade, ${L.year}` : ""} />
          <Kpi label="Trade under a trade agreement" value={P ? fmtPct(P.pta_trade_share) : "–"} sub={P ? `share in ${P.year} (agreement data ends 2019)` : "agreement data covers 1986–2019"} />
          <Kpi label="Exporting economies" value={L && ey === L.year ? fmtNum(exporters.filter((r) => r.year === ey && r.usd_m > 0).length) : "–"} sub={L ? `with positive exports, ${L.year}` : ""} />
        </div>

        <div className="tx-grid">
          <Card w={8} title="World trade by sector" sub={`Cross-border trade, current US dollars · ${selection}. Hover for the yearly total.`}>
            <Legend items={SECTORS.map((s) => ({ label: s, color: p.sectors[s], square: true }))} />
            {sectors.loading && !sectorRows.length ? <Skel h={420} /> : sectorRows.length ? <VegaChart spec={areaSpec} data={sectorRows} /> : <Empty />}
            <Explain title="Coverage changes:">
              ITPD-E includes services only from 2000 and changes its services sources in 2004 and 2010, so jumps in the purple
              band are partly coverage, not real growth. Pick a single sector above for a like-for-like trend.
            </Explain>
          </Card>
          <Card w={4} title={`Top exporters${ey ? ` (${ey})` : ""}`} sub={`Share of world exports, with rank in ${ef ?? "the first year"}.`}>
            {expQ.loading && !leaders.length ? <Skel h={420} /> : leaders.length ? <BarList rows={leaders} /> : <Empty />}
          </Card>

          <Card w={6} title={`Who sells to whom?${fy ? ` (${fy})` : ""}`} sub="Cross-border trade between UN regions, exporter region (rows) → importer region (columns), $ billions. The diagonal is trade within a region.">
            {flows.loading && !flows.rows.length ? (
              <Skel h={260} />
            ) : (
              <table className="tx-heat">
                <thead>
                  <tr>
                    <th>From ↓ / To →</th>
                    {matrix.regs.map((r) => (
                      <th key={r}>{r}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {matrix.regs.map((a) => (
                    <tr key={a}>
                      <th>
                        <span className="tx-dot" style={{ background: p.regions[a], marginRight: 6, width: 8, height: 8 }} />
                        {a}
                      </th>
                      {matrix.regs.map((b) => {
                        const v = matrix.get(a, b);
                        return (
                          <td key={b} style={{ ...heat(v), outline: a === b ? `2px solid ${p.ink2}` : "none", outlineOffset: -2 }} title={`${a} → ${b}: ${fmtUSD(v)}`}>
                            {v >= 1000 ? `${Math.round(v / 1000).toLocaleString()}` : v > 0 ? (v / 1000).toFixed(1) : "–"}
                          </td>
                        );
                      })}
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
            <Explain title="Regional blocs:">
              Europe and Asia trade mostly with themselves — the outlined diagonal cells — thanks to short distances, deep supply
              chains and agreements like the EU single market.
            </Explain>
          </Card>
          <Card w={6} title="Is trade becoming more regional?" sub="Share of cross-border trade within the same UN region, and between partners with a trade agreement (to 2019).">
            <Legend items={[{ label: "Within the same region", color: p.A }, { label: "Covered by a trade agreement", color: p.B }]} />
            {structure.loading && !shareRows.length ? <Skel h={230} /> : shareRows.length ? <VegaChart spec={shareSpec} data={shareRows} /> : <Empty />}
            <Explain title="The rise of trade agreements:">
              the number of preferential trade agreements exploded after the 1990s, and a growing share of world trade now moves
              between partners that have one.
            </Explain>
          </Card>

          <Card w={6} title="Who exports? Rich and poor economies" sub="Share of world exports by the exporter's World Bank income group in that year.">
            <Legend items={INCOME.map((g, i) => ({ label: g, color: (dark ? INCOME_RAMP.dark : INCOME_RAMP.light)[i], square: true }))} />
            {income.loading && !incRows.length ? <Skel h={230} /> : incRows.length ? <VegaChart spec={incSpec} data={incRows.map((r) => ({ ...r, rank: INCOME.indexOf(r.group) }))} /> : <Empty />}
            <Explain title="Countries move between groups:">
              the income group is the one the country had in each year — so China's shift from lower-middle to upper-middle income
              (2010) moves its exports between bands.
            </Explain>
          </Card>
          <Card w={6} title="Is distance dead?" sub="Average distance travelled by a dollar of cross-border trade (trade-weighted, km; gravity data to 2019).">
            {structure.loading && !distRows.length ? <Skel h={230} /> : distRows.length ? <VegaChart spec={distSpec} data={distRows} /> : <Empty />}
            <Explain title="Distance still matters:">
              despite cheaper shipping and the internet, the average dollar of trade still travels only about 5,000 km — far
              less than the distance between random pairs of countries. Most trade is with neighbours, just as the gravity model
              predicts.
            </Explain>
          </Card>
        </div>
      </main>
    </>
  );
}

// ── International Trade Explorer: one page, three tabs ───────────────────────
// All three views live in ONE dashboard so the browser downloads the data once
// per visit. A tab is mounted the first time it is opened and then kept mounted
// (hidden when inactive), so its filters, results and scroll position survive
// switching away and back; after the first view loads, the other tabs warm up
// in the background. Each tab reads only its own givens (B_/C_/W_ plus
// its country pickers), so a change on one tab never re-runs another tab.

const TABS = [
  { id: "bilateral", label: "Two countries", hint: "Bilateral trade between A and B", Comp: BilateralTab },
  { id: "country", label: "One country", hint: "Where a country's trade goes", Comp: CountryTab },
  { id: "world", label: "The world", hint: "Global trade at a glance", Comp: WorldTab },
];

const TAB_CSS = `
.tx-tabs{position:sticky;top:0;z-index:20;display:flex;align-items:center;gap:6px;padding:8px 32px;
  background:color-mix(in srgb,var(--hero1) 92%,transparent);backdrop-filter:blur(8px);border-bottom:1px solid rgba(255,255,255,.08)}
.tx-tabs .brand{display:flex;flex-direction:column;line-height:1.2;margin-right:14px;white-space:nowrap}
.tx-tabs .brand .name{color:#fff;font-weight:700;letter-spacing:-.01em}
.tx-tabs button{font:inherit;font-size:13.5px;color:#c9d6e6;background:transparent;border:1px solid transparent;border-radius:999px;
  padding:6px 14px;cursor:pointer;display:flex;flex-direction:column;align-items:flex-start;line-height:1.2}
.tx-tabs button small{font-size:11px;color:#8ea6c4}
.tx-tabs button:hover{background:rgba(255,255,255,.08);color:#fff}
.tx-tabs button.on{background:#fff;color:#0b1d33;font-weight:650}
.tx-tabs button.on small{color:#52514e}
.tx-tabs .status{margin-left:auto;font-size:12px;color:#9cc3f0;display:flex;align-items:center;gap:8px;white-space:nowrap}
.tx-tabs .source{margin-left:auto;font-size:12.5px;color:#c9d6e6;text-decoration:none;white-space:nowrap;padding:5px 11px;border-radius:999px;border:1px solid rgba(255,255,255,.16);background:rgba(255,255,255,.06)}
.tx-tabs .source:hover{color:#fff;background:rgba(255,255,255,.14)}
.tx-tabs .spin{width:12px;height:12px;border-radius:50%;border:2px solid rgba(156,195,240,.35);border-top-color:#9cc3f0;animation:txspin .8s linear infinite}
@keyframes txspin{to{transform:rotate(360deg)}}
@media (max-width:760px){.tx-tabs{padding:8px 12px;overflow-x:auto}.tx-tabs button small{display:none}.tx-tabs .brand .name{font-size:13px}}
`;

export default function Dashboard({ givens }) {
  const [tab, setTab] = useUrlState("tab", "bilateral");
  const [visited, setVisited] = useState(() => new Set([tab]));
  useEffect(() => {
    setVisited((v) => (v.has(tab) ? v : new Set([...v, tab])));
  }, [tab]);

  // The first query of the session waits for the data download; show that once.
  const probe = useQuery({ query: "b_pair_countries", givens: pickGivens(givens, ["COUNTRY_A", "COUNTRY_B"]) });
  const [ready, setReady] = useState(false);
  useEffect(() => {
    if (!probe.loading && (probe.rows.length || probe.error)) setReady(true);
  }, [probe.loading, probe.rows.length, probe.error]);

  // Warm-up: once the first view has its data, mount the other tabs (hidden) so
  // their queries run in the background and they are ready when clicked.
  useEffect(() => {
    if (!ready) return undefined;
    const t = setTimeout(() => setVisited(new Set(TABS.map((x) => x.id))), 1500);
    return () => clearTimeout(t);
  }, [ready]);

  // "Compare" from the One country tab: open Two countries with A = that country, B = partner.
  const A = useGiven("COUNTRY_A");
  const B = useGiven("COUNTRY_B");
  const compare = (a, b) => {
    A.set(filters.oneOf(a));
    B.set(filters.oneOf(b));
    go("bilateral");
  };

  const go = (id) => {
    setTab(id);
    window.scrollTo({ top: 0 });
    // Charts in a tab that was hidden size themselves on resize; nudge them.
    setTimeout(() => window.dispatchEvent(new Event("resize")), 30);
  };

  return (
    <Shell>
      <style>{TAB_CSS}</style>
      <nav className="tx-tabs" aria-label="Views">
        <div className="brand">
          <span className="name">International Trade Explorer</span>
        </div>
        {TABS.map((t) => (
          <button key={t.id} className={tab === t.id ? "on" : ""} onClick={() => go(t.id)} aria-current={tab === t.id ? "page" : undefined}>
            {t.label}
            <small>{t.hint}</small>
          </button>
        ))}
        {ready ? (
          <a className="source" href="https://www.usitc.gov/data/gravity/gravity_portal_itpd_e" target="_blank" rel="noopener noreferrer">
            Using ITPD-E data ↗
          </a>
        ) : (
          <span className="status">
            <span className="spin" />
            Loading trade data (first visit only)…
          </span>
        )}
      </nav>
      {TABS.map(({ id, Comp }) =>
        visited.has(id) ? (
          <div key={id} style={{ display: tab === id ? "block" : "none" }}>
            <Comp givens={givens} onCompare={compare} />
          </div>
        ) : null,
      )}
      <div className="tx-body" style={{ paddingTop: 0 }}>
        <Footer />
      </div>
    </Shell>
  );
}
