#!/usr/bin/env python3
"""Assemble dashboards/trade.jsx from the shared UI kit + the three tabs.

Dashboard components may only import React and @malloyyo/dashboard, so the
pieces are concatenated into one file. Edit files in dashboard_src/, then run:

    python3 dashboard_src/build.py
"""
import pathlib

src = pathlib.Path(__file__).resolve().parent
parts = ["common.jsx", "tab_bilateral.jsx", "tab_country.jsx", "tab_world.jsx", "trade.page.jsx"]
header = "// GENERATED by dashboard_src/build.py from " + " + ".join(parts) + " — edit those, not this file.\n"
body = "\n".join((src / p).read_text() for p in parts)
out = src.parent / "dashboards" / "trade.jsx"
out.write_text(header + body)
print("wrote", out)
